### PR TITLE
Finish translating control-flow.rst

### PR DESCRIPTION
**Pull request by yuyichao**
First contribution.

Submit a PR to get feedback and to make sure I'm following the convensions.

I'll merge one week later if no one object.

### CODE REVIEW

**Comment by yuyichao** [comment]
P.S. Sorry I've `push --force`'d on master just now to revert this commit... (Forgot to `checkout -b` before I pushed.....)

**Comment by GaZ3ll3** [comment]
i think it is good to merge.

**Comment by wlbksy** [comment]
尽管push就好了……最多不过丢了blame而已

**Comment by yuyichao** [comment]
.... 我 blame 从来都是要追溯好几级的......
嘛 那我下次就直接 push 了.....

**Pull request merged**
